name: JoinLeaveMessage
version: '${project.version}'
main: me.alkaison.joinleavemessage.JoinLeaveMessage
api-version: 1.19
authors: [ Alkaison ]
description: A plugin to set custom leave and join messages.
